#!/bin/bash

program="pcMonitor"
filename=`readlink -f "${BASH_SOURCE[0]}"`
basedir=`dirname "${filename}"`
binary="${basedir}/bin/${EPICS_HOST_ARCH}/${program}"

tmpfile=`mktemp startup-XXXXXX`
trap "{ ret=$?; rm -f \"$tmpfile\"; exit $ret; }" EXIT
cat >"$tmpfile" <<__EOF__

# Begin of EPICS commands to start application
epicsEnvSet("IOC","${program}")
epicsEnvSet("TOP","${basedir}")
epicsEnvSet("EPICS_BASE","${EPICS_BASE}")

## Register all support components
dbLoadDatabase("\${TOP}/dbd/${program}.dbd", 0, 0)
${program}_registerRecordDeviceDriver pdbbase

## Load record instances
dbLoadTemplate("\${TOP}/iocBoot/ioc/pcMonitor.substitutions","IOC=\${IOC}")

iocInit

# end of predefined EPICS commands
__EOF__

"${binary}" "$tmpfile"
